### PR TITLE
Add noarch: python

### LINKED ISSUE #311: @conda-forge-admin, please add noarch: python
### Additional comment:

Xref #192

### PR DESCRIPTION
**Pull request by weiji14**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Supersedes and closes #312. Fixes #311 and #192.

### CODE REVIEW

**Comment by weiji14** [comment]
@conda-forge-admin, please rerender

**Review by efiop — APPROVED** [review]
Thanks @weiji14 ! Great stuff!

I see you've also added yourself to maintainers, so I guess you won't mind if we ping you if this breaks 😅

**Comment by weiji14** [comment]
Yes, happy to patch things if it doesn't work as expected 🙂

**Comment by efiop** [comment]
@weiji14 Btw, just a heads up: https://github.com/orgs/iterative/people/jendefig will be reaching out to you on linkedin to send you some merch from us as a small gratitude for your contribution 🙂

**Pull request merged**
