### PR TITLE
Fix incorrect fsspec version

### PR DESCRIPTION
**Pull request by maresb**
It should be in agreement with https://github.com/iterative/dvc/blob/2.0.18/setup.py

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
This is odd. The problem is that [it's installing an old build of argcomplete](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=307405&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=2853). For reference, [here are all the builds](https://anaconda.org/conda-forge/argcomplete/files).

**Comment by maresb** [comment]
@conda-forge-admin please restart ci

**Comment by maresb** [comment]
Ok, excellent. Hopefully I fixed the problem upstream. If someone could restart CI in 1½ hours we can see if it worked.

**Comment by efiop** [comment]
@maresb Thank you! Btw, please feel free to add yourself to the maintainers, if that will help you. Thanks again for the contributions! :pray:

**Comment by maresb** [comment]
Thanks @efiop! I added myself as a maintainer.

In case you're still around in an hour, could you please restart the ci? Then we'll see whether or not the issue is fixed. (If it passes it should be fine to merge.) Otherwise I'll take care of it sometime tomorrow.

@conda-forge-admin please rerender

**Comment by maresb** [comment]
@conda-forge-admin please restart ci

**Pull request merged**
