### PR TITLE
Remove temporary upstream importlib-meta dependency

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [ ] Bumped the build number (if the version is unchanged)

Once both #208 is merged and the issue described in conda-forge/filesystem-spec-feedstock/issues/42 and conda-forge/filesystem-spec-feedstock#43 is resolved, then do the following:

- Write the following in a comment in this PR, adding a @ at the front of conda-forge-admin in order to ping the bot:
  > conda-forge-admin, please restart ci
- Fix any additional problems.
- Bump the build number!!!!! (I can't do it beforehand since I don't know the order in which the upstream issues will resolve.)
- Merge this.

### CODE REVIEW

**Comment by maresb** [comment]
The upstream fix didn't work.

**Comment by maresb** [comment]
A new fix, conda-forge/filesystem-spec-feedstock#48 has been merged.
@conda-forge-admin, please restart ci

**Comment by maresb** [comment]
Strange... Python 3.7 on Linux failed because it pulled the old build, but it succeeded elsewhere. Maybe there is some glitch with the conda-forge CDN? Let's try again...

@conda-forge-admin, please restart ci

**Comment by maresb** [comment]
Finally!!! Ready to merge! :rocket:

**Comment by efiop** [comment]
@maresb Thank you! :pray:

**Pull request merged**
