### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #192.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by skshetry** [comment]
@conda-forge-admin, please add python 3.9

**Comment by skshetry** [comment]
@conda-forge-admin, please add noarch: python

**Comment by skshetry** [comment]
@conda-forge-admin please rerender

**Comment by skshetry** [comment]
@conda-forge-admin, please add python 39

**Comment by skshetry** [comment]
@conda-forge-admin, please add python 3.9

**Comment by weiji14** [comment]
> 
> Hi! This is the friendly automated conda-forge-linting service.
> 
> I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.
> 
> Here's what I've got...
> 
> 
> For **recipe**:
> 
>  * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
> 

According to https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds, it says:

> Note: While noarch: python does not work with selectors, it does work with version constraints. skip: True  # [py2k] can be replaced with a constrained python version in the host and run subsections: say python >=3 instead of just python

Not quite sure what to make from this, does that mean noarch doesn't work at all? Or that noarch works but Python version constraints must be used :/

**Comment by weiji14** [comment]
> > * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.
> 
> According to https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds, it says:
> 
> > Note: While noarch: python does not work with selectors, it does work with version constraints. skip: True  # [py2k] can be replaced with a constrained python version in the host and run subsections: say python >=3 instead of just python
> 
> Not quite sure what to make from this, does that mean noarch doesn't work at all? Or that noarch works but Python version constraints must be used :/

Ah I think I get it, maybe remove this line:

https://github.com/conda-forge/dvc-feedstock/blob/6ec77357282e02dc3804bd75149205da458d922c/recipe/meta.yaml#L19

And then change all the `python` instances in recipe/meta.yaml to `python >=3.7`

**Comment by skshetry** [comment]
@conda-forge-admin please rerender

**Comment by skshetry** [comment]
Looks like we are in awaiting PR mode. Let's see if the python 3.9 PR drops, and then make a decision about noarch builds.

**Comment by skshetry** [comment]
@conda-forge-admin, please add python 3.9

**Comment by skshetry** [comment]
@conda-forge-admin please rerender

**Pull request closed without merging**
