### PR TITLE
fix azure build failure

### PR DESCRIPTION
**Pull request by efiop**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@efiop it's not your fault. See https://conda-forge.org/status/, in particular https://github.com/conda-forge/status/issues/117

**Comment by maresb** [comment]
Even better, see https://dev.azure.com/conda-forge/feedstock-builds/_build?definitionId=7270

**Comment by maresb** [comment]
Ah, sorry if I misunderstood, it looks like it is failing anyways. So you were probably already aware. :smile:

**Comment by efiop** [comment]
@maresb Thanks for pointing that out! :pray: 

Yeah, I've noticed that there are no checks triggered, but accidentally merged some PRs anyway. The azure issue has been around for a few days already, so just creating this WIP to not forget about it when CI comes back to life.

**Comment by maresb** [comment]
By using the last link I wrote, I think that you could still debug the issue, right? (It seems that the CI is still running, just not linked with these "checks" here on GitHub.) Or is there some complication?

**Comment by efiop** [comment]
Hm, looks like we now have an unrelated conflict on windows. A little confused by what is exactly conflicting, the logs are overloaded with conflicts.

**Comment by maresb** [comment]
@efiop, since Mamba often gives more sensible error messages, I just tried building locally on LInux with `conda mambabuild .` and got
```
msal-extensions 0.3.0 has requirement portalocker~=1.0; platform_system != "Windows", but you have portalocker 2.3.0.
```
I'm not sure at the moment where those dependencies are coming from.

**Comment by efiop** [comment]
@maresb That one is the same as what was reported by `pip check`. There is something else going on specifically on windows with python 3.9 Investigating...

**Comment by efiop** [comment]
@maresb Thank you for getting to the bottom of it! :pray:

**Pull request merged**
